import { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "./_components/Providers";


const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] });


export const metadata: Metadata = {
  title: "Dossier",
  description: "Generated by create next app",

  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <head>
        {/* ✅ Correct Google Site Verification Meta Tag */}
        <meta name="google-site-verification" content="XjZDapxRkhfclv7cOugD-GDwHOaoheZ2zBILyiF-XtI" />
      </head>
      <body className={`${roboto.className} dark:text-white dark:bg-black bg-theme-light`}>
       
          <Providers>{children}</Providers>
      
      </body>
    </html>
  );
}
