import { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import { siteConfig } from "@/lib/siteConfig";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

// export const metadata: Metadata = {
//   title: "Dossier",
//   description: "Generated by create next app",

//   icons: {
//     icon: '/favicon.ico',
//   },
// };
export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.name}`,
  },
  metadataBase: new URL(siteConfig.url),
  description: siteConfig.description,
  keywords: [
    "online portfolio builder",
    "resume and portfolio generator",
    "personal portfolio creator",
    "developer portfolio website",
    "freelancer portfolio builder",
    "portfolio website for students",
    "customizable portfolio templates",
    "one-click resume download",
    "showcase projects and skills",
    "professional portfolio maker",
  ],
  authors: [
    {
      name: "Dossier",
      url: "https://ankushjaiswal.vercel.app",
    },
  ],
  creator: "Dossier",
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: siteConfig.name,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: "@obviouslyanku",
  },
  icons: {
    icon: [
      {
        type: "image/png",
        sizes: "16x16",
        media: "(prefers-color-scheme: light)",
        url: "/meta/favicon-16x16.png",
      },
      {
        type: "image/png",
        sizes: "16x16",
        media: "(prefers-color-scheme: dark)",
        url: "/meta/dark/favicon-16x16.png",
      },
      {
        type: "image/png",
        sizes: "32x32",
        media: "(prefers-color-scheme: light)",
        url: "/meta/favicon-32x32.png",
      },
      {
        type: "image/png",
        sizes: "32x32",
        media: "(prefers-color-scheme: dark)",
        url: "/meta/dark/favicon-32x32.png",
      },
    ],
    shortcut: [
      {
        type: "image/x-icon",
        media: "(prefers-color-scheme: light)",
        url: "/meta/favicon.ico",
      },
      {
        type: "image/x-icon",
        media: "(prefers-color-scheme: dark)",
        url: "/meta/dark/favicon.ico",
      },
    ],
    apple: [
      {
        type: "image/png",
        sizes: "180x180",
        media: "(prefers-color-scheme: light)",
        url: "/meta/apple-touch-icon.png",
      },
      {
        type: "image/png",
        sizes: "180x180",
        media: "(prefers-color-scheme: dark)",
        url: "/meta/dark/apple-touch-icon.png",
      },
    ],
  },
  manifest: `/site.webmanifest`,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Correct Google Site Verification Meta Tag */}
        <meta
          name="google-site-verification"
          content="XjZDapxRkhfclv7cOugD-GDwHOaoheZ2zBILyiF-XtI"
        />
      </head>
      <body
        className={`${roboto.className} dark:text-white dark:bg-black bg-theme-light`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
